# Generated by Django 4.2.7 on 2023-11-12 14:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Добавить категорию')),
                ('image', models.ImageField(upload_to='product-category/%Y_%m', verbose_name='Картинка категории')),
            ],
            options={
                'verbose_name': '1 Тип товара',
                'verbose_name_plural': '1 Типы товаров',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подкатегория')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название товара')),
                ('product_code', models.CharField(max_length=100, verbose_name='Код товара')),
                ('pack', models.CharField(max_length=20, verbose_name='(Если упаковано - null) или "/480" г')),
                ('old_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая цена (обновите если цена устела)')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('price_for', models.CharField(choices=[('1', 'сом/кг'), ('2', 'сом/шт')], max_length=50, verbose_name='тип цены кг/штук')),
                ('images', models.ImageField(upload_to='product-detail/%Y_%m', verbose_name='Картинка товара')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sub_cat', smart_selects.db_fields.GroupedForeignKey(group_field='cat', on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'verbose_name': '2 Продукт',
                'verbose_name_plural': '2 Продукты',
            },
        ),
    ]
