# Generated by Django 4.2.7 on 2023-12-23 13:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='product-category/%Y_%m', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Показать в мобильном приложении')),
                ('title', models.CharField(max_length=300, verbose_name='Название товара')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код товара')),
                ('old_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старая цена')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('price_for', models.CharField(choices=[('кг', 'кг'), ('шт', 'шт')], default='шт', verbose_name='Цена за')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product-detail/%Y_%m', verbose_name='Изображение')),
                ('sales', models.IntegerField(default=0, verbose_name='Количество продаж')),
                ('quantity', models.CharField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категория')),
                ('sub_cat', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='cat', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
