# Generated by Django 4.2.7 on 2023-11-12 15:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cat', chained_model_field='cat', on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория'),
        ),
    ]
