# Generated by Django 4.2.7 on 2023-12-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnloadedCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('guid', models.CharField(max_length=255, verbose_name='GUID')),
            ],
            options={
                'verbose_name': 'Категория выгрузки',
                'verbose_name_plural': 'Категории выгрузки',
            },
        ),
        migrations.CreateModel(
            name='UnloadedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID продукта')),
                ('barrcode', models.IntegerField(blank=True, null=True, verbose_name='Штрих-код')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена')),
                ('discounted_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена со скидкой')),
                ('quantity', models.CharField(blank=True, max_length=30, null=True, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unloadedcategories')),
            ],
            options={
                'verbose_name': 'Продукт выгрузки',
                'verbose_name_plural': 'Продукты выгрузки',
            },
        ),
    ]
