# Generated by Django 4.2.7 on 2023-12-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_unloadedcategories_unloadedproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unloadedcategories',
            options={'verbose_name': 'Выгруженная категория', 'verbose_name_plural': 'Выгруженные категории'},
        ),
        migrations.AlterModelOptions(
            name='unloadedproducts',
            options={'verbose_name': 'Выгруженный продукт', 'verbose_name_plural': 'Выгруженные продукты'},
        ),
    ]
