# Generated by Django 4.2.7 on 2023-11-12 15:26

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='cat', on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
