# Generated by Django 4.2.7 on 2023-11-12 15:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_category_img_rename_images_product_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='product-category/%Y_%m', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='cat', on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
