# Generated by Django 4.2.7 on 2023-12-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_unloadedproducts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='barrcode',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='unloadedproducts',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='barrcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='unloadedproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='unloadedproducts',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
