# Generated by Django 4.2.7 on 2023-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_code_product_code_alter_category_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
