# Generated by Django 4.2.7 on 2023-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barrcode',
            field=models.CharField(blank=True, null=True, verbose_name='Штрих-код'),
        ),
    ]
