# Generated by Django 4.2.7 on 2023-12-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_barrcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unloadedcategories',
            options={'verbose_name': '1C категория', 'verbose_name_plural': '1C категории'},
        ),
        migrations.AlterModelOptions(
            name='unloadedproducts',
            options={'verbose_name': '1C Выгрузка', 'verbose_name_plural': '1C Выгрузка'},
        ),
    ]
