# Generated by Django 4.2.7 on 2023-11-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_cat_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_for',
            field=models.IntegerField(choices=[(1, 'кг'), (2, 'шт')], max_length=50, verbose_name='Цена за'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='Категория'),
        ),
    ]
