# Generated by Django 4.2.7 on 2023-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price_for_alter_subcategory_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='Количество продаж'),
        ),
    ]
