# Generated by Django 4.2.7 on 2023-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='шт', max_length=2, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for',
            field=models.IntegerField(choices=[('кг', 'кг'), ('шт', 'шт')], verbose_name='Цена за'),
        ),
    ]
