# Generated by Django 4.2.7 on 2023-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_price_alter_product_price_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for',
            field=models.CharField(choices=[('кг', 'кг'), ('шт', 'шт')], default='шт', verbose_name='Цена за'),
        ),
    ]
