# Generated by Django 4.2.7 on 2023-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_price_alter_product_price_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Показать в мобильном приложении'),
        ),
    ]
