# Generated by Django 4.2.7 on 2023-12-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_product_id',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Айди товара в 1C'),
        ),
    ]
