# Generated by Django 4.2.7 on 2023-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(unique=True, verbose_name='Номер телефона'),
        ),
    ]
