# Generated by Django 4.2.7 on 2024-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rollrequest_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_request',
            field=models.BooleanField(default=False, verbose_name='Запрос на контрагент уже есть'),
        ),
    ]
