# Generated by Django 4.2.7 on 2024-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(default=False, verbose_name='Оптовик'),
        ),
    ]
