# Generated by Django 4.2.7 on 2023-11-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_bonus_alter_user_bonus_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='qrimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QRcode Пользователя'),
        ),
    ]
