# Generated by Django 4.2.7 on 2023-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus_id',
            field=models.CharField(blank=True, null=True, verbose_name='Бонусный ID'),
        ),
    ]
