# Generated by Django 4.2.7 on 2023-11-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('Кыргызча', 'Кыргызча'), ('Русский', 'Русский')], max_length=50, null=True, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='married',
            field=models.CharField(blank=True, choices=[('Холост/не замужем', 'Холост/не замужем'), ('Женат/замужем', 'Женат/замужем')], max_length=100, null=True, verbose_name='Семейное положение'),
        ),
    ]
