# Generated by Django 4.2.7 on 2023-11-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_gender_alter_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Получать уведомления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
    ]
