# Generated by Django 4.2.7 on 2023-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_brightness',
            field=models.BooleanField(default=False, verbose_name='Авто яркость'),
        ),
    ]
