# Generated by Django 4.2.7 on 2024-01-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_deliveryaddress_apartment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='city',
            new_name='address',
        ),
    ]
