# Generated by Django 4.2.7 on 2024-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='sum',
            field=models.CharField(blank=True, null=True, verbose_name='Общая сумма'),
        ),
    ]
