# Generated by Django 4.2.7 on 2024-01-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordertable_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='count',
            field=models.CharField(blank=True, null=True, verbose_name='Общее количество'),
        ),
    ]
