# Generated by Django 4.2.7 on 2024-01-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_productinline_relatedname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinline',
            old_name='relatedname',
            new_name='order',
        ),
    ]
