# Generated by Django 4.2.7 on 2024-01-08 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_wholesale_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_ordertable_ordertableinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertable',
            options={'verbose_name': 'Таблица заказов', 'verbose_name_plural': 'Таблица заказов'},
        ),
        migrations.AddField(
            model_name='ordertableinfo',
            name='user_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='ordertableinfo',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_info', to='order.ordertable'),
        ),
        migrations.AlterField(
            model_name='ordertableinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
