# Generated by Django 4.2.7 on 2024-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordertable_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая сумма'),
        ),
    ]
