# Generated by Django 4.2.7 on 2024-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordertable_count_alter_ordertable_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertableinfo',
            name='sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
