# Generated by Django 4.2.7 on 2024-01-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordertable_options_ordertableinfo_user_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата и время заказа'),
        ),
    ]
