# Generated by Django 4.2.7 on 2024-01-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordertableinfo_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='sum',
        ),
    ]
