# Generated by Django 4.2.7 on 2024-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_relatedname_productinline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Телефон номер'),
        ),
    ]
