# Generated by Django 4.2.7 on 2024-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinline',
            name='price_for',
            field=models.CharField(blank=True, null=True, verbose_name='Цена за'),
        ),
    ]
