# Generated by Django 4.2.7 on 2024-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=150, verbose_name='Токен')),
                ('chat_id', models.CharField(help_text='ID группы можно узнать в веб-версии Telegram.', max_length=50, verbose_name='ID группы')),
            ],
            options={
                'verbose_name': 'Телеграм Бот',
                'verbose_name_plural': '1. Телеграм Бот',
            },
        ),
    ]
