# Generated by Django 4.2.7 on 2024-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_productinline_price_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='product',
            field=models.CharField(blank=True, null=True, verbose_name='Товар'),
        ),
    ]
