# Generated by Django 4.2.7 on 2024-01-04 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_telebot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telebot',
            options={'verbose_name': 'Телеграм Бот', 'verbose_name_plural': 'Настройка телеграм бота'},
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
