# Generated by Django 4.2.7 on 2024-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_ordertable_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertableinfo',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Доставлено!'),
        ),
        migrations.AlterField(
            model_name='ordertableinfo',
            name='user_info',
            field=models.CharField(blank=True, default=120, max_length=200, null=True, verbose_name='ФИО'),
        ),
    ]
