# Generated by Django 4.2.7 on 2023-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stories_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='link',
            field=models.URLField(blank=True, help_text='Если есть', max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
