# Generated by Django 4.2.7 on 2023-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stories_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('from_date_after', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('to_date_after', models.CharField(blank=True, editable=False, max_length=5, null=True)),
                ('type', models.CharField(choices=[('1', 'Успей купить'), ('2', 'Специальные предложения')], max_length=50, verbose_name='Тип')),
                ('title', models.CharField(help_text='Успей купить!', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='promotions/%Y_%m', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки (Акция/Предложения)',
            },
        ),
    ]
