# Generated by Django 4.2.7 on 2023-11-13 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_from_date_cards_datefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='datefrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала акции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='dateto',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания акции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.IntegerField(choices=[(1, 'Успей купить'), (2, 'Специальные предложения')], verbose_name='Тип'),
        ),
    ]
