# Generated by Django 4.2.7 on 2023-11-20 08:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cards_datefrom_alter_cards_dateto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
