# Generated by Django 4.2.7 on 2023-11-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cards_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Действует до:'),
        ),
    ]
