# Generated by Django 4.2.7 on 2023-11-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cards_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='date',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Действует до:'),
        ),
    ]
