# Generated by Django 4.2.7 on 2023-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cards_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Версия')),
                ('appstore', models.URLField(verbose_name='App Store')),
                ('googleplay', models.URLField(verbose_name='Google Play')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Версия приложения',
                'verbose_name_plural': 'Версии приложения',
            },
        ),
    ]
