# Generated by Django 4.2.7 on 2023-12-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notifications_notificationsimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Уведомления', 'verbose_name_plural': 'Уведомлении'},
        ),
        migrations.AlterModelOptions(
            name='notificationsimg',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='notificationsimg',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='main.notifications'),
        ),
    ]
