# Generated by Django 4.2.7 on 2023-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='type',
            field=models.IntegerField(choices=[(1, 'Акция'), (2, 'Специальные предложения')], verbose_name='Тип'),
        ),
    ]
